Row and column getter
becheran/grid pull request #55
Opened 2024-08-22 16:46 UTC by ibarrond

Adds `get_row` and `get_col` to access the corresponding underlying slices, returning None if out of bounds or if the values are not contiguous (e.g., a row in `Order::ColumnMajor` or a column in `Order::RowMajor`). 

Equivalent mutable methods `get_mut_row` and `get_mut_col`.

EXTRA: some quick linter fixes.

2024-08-28 14:14 UTC, ibarrond commented
@becheran Any chance this can be merged sometime soon?

2024-08-31 21:12 UTC, becheran requested changes
First of all thanks for openening a PR.

I don't understand why those additional function whould make the library more useful? Especially because all function only work properly in one of the two modes.

2024-08-31 21:12 UTC, becheran commented on src/lib.rs
> +            None
I had a look at the changes. Thanks for the formatting. I better setup my auto-formatter better.

I wonder if the implementaiton helps or is more confusing. I don't think it is a good idea to expose a function called `get_row` which only works in `RowMajor` mode.

Why not use the already existing `iter_row` funciton instead and let the caller decide if collecting the result into a `Vec` is desired?

2025-04-19 08:49 UTC, becheran commented
Decided to reject the PR since I do not see much benefit. Still thanks for opening the PR. At least it showed me that I needed to add a formatter check in my pipeline.

2025-04-19 08:49 UTC, closed without merging