feat: add a map and map_ref method
becheran/grid pull request #61
Opened 2024-12-16 17:22 UTC by henryiii

This adds a way to apply a function (possibly changing the type) and produce a new Grid. For example, given a grid, you could produce a mask by applying a function producing a boolean.

2024-12-18 20:25 UTC, becheran requested changes
Looks really useful. Thanks for adding the feature!

Just adding at least one test for each function would be great. Otherwise no issues.

2024-12-18 20:59 UTC, henryiii commented
I added doctests for each, I guess you mean unit tests too? I can do that.

2024-12-18 21:55 UTC, henryiii commented
Done! Let me know if you want anything else, more testing, etc.

2024-12-19 18:54 UTC, becheran approved these changes

2024-12-19 18:55 UTC, merged

2024-12-19 18:55 UTC, becheran commented
I forgot about the doctests, which you already added. Would have been enough, I just did not realize them.

=> Thanks! Merged

2024-12-19 19:08 UTC, henryiii commented
The methods around it also had regular tests (and regular tests are faster), so seemed reasonable to have those too. :)